# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.270
  hooks:
    - id: ruff
- repo: local
  hooks:
    - id: lupdate
      name: lupdate
      entry: powershell ./scripts/build/windows/lupdate.ps1
      pass_filenames: false
      always_run: true
      language: python
      types: [python]
